menu:
  Home: /
  Archives: /archives

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter: onion2k
github: onion2k

fancybox: true
google_analytics:
rss: