menu:
  Ooer.com: http://www.ooer.com
  Library: /
  Archive: /archives

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

facebook:
google_plus:
twitter: onion2k
github: onion2k

fancybox:
google_analytics:
rss: